-- 기존 쇼핑 데이터
INSERT INTO item_category (parent_option, option_value) VALUES (NULL, '강아지');
INSERT INTO item_category (parent_option, option_value) VALUES (1, '사료');
INSERT INTO item_category (parent_option, option_value) VALUES (1, '간식');
INSERT INTO item_category (parent_option, option_value) VALUES (1, '영양제');
INSERT INTO item_category (parent_option, option_value) VALUES (1, '장난감');
INSERT INTO item_category (parent_option, option_value) VALUES (1, '용품');
INSERT INTO item_category (parent_option, option_value) VALUES (NULL, '고양이');
INSERT INTO item_category (parent_option, option_value) VALUES (7, '사료');
INSERT INTO item_category (parent_option, option_value) VALUES (7, '간식');
INSERT INTO item_category (parent_option, option_value) VALUES (7, '영양제');
INSERT INTO item_category (parent_option, option_value) VALUES (7, '장난감');
INSERT INTO item_category (parent_option, option_value) VALUES (7, '용품');
INSERT INTO item_category (parent_option, option_value) VALUES (NULL, '기타');
INSERT INTO item_category (parent_option, option_value) VALUES (13, '기타');


INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (2, '강아지 사료 상품1', '강아지의 사료용 고급 상품입니다.', 13200, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 5800, 17, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 29900, 24, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_food_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (2, '강아지 사료 상품2', '강아지의 사료용 고급 상품입니다.', 10200, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 4000, 25, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 22200, 34, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_food_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (2, '강아지 사료 상품3', '강아지의 사료용 고급 상품입니다.', 26700, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 24900, 7, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 15100, 8, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_food_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (2, '강아지 사료 상품4', '강아지의 사료용 고급 상품입니다.', 16700, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 10900, 27, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 29500, 50, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_food_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (2, '강아지 사료 상품5', '강아지의 사료용 고급 상품입니다.', 5300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 12700, 25, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 4000, 7, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_food_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (3, '강아지 간식 상품1', '강아지의 간식용 고급 상품입니다.', 16900, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 21100, 37, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 22700, 38, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_snack_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (3, '강아지 간식 상품2', '강아지의 간식용 고급 상품입니다.', 12200, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 26900, 15, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 14800, 26, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_snack_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (3, '강아지 간식 상품3', '강아지의 간식용 고급 상품입니다.', 19500, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 1000, 50, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 20200, 32, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_snack_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (3, '강아지 간식 상품4', '강아지의 간식용 고급 상품입니다.', 6300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 11000, 44, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 6000, 9, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_snack_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (3, '강아지 간식 상품5', '강아지의 간식용 고급 상품입니다.', 15400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 9300, 42, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 28400, 8, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_snack_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (4, '강아지 영양제 상품1', '강아지의 영양제용 고급 상품입니다.', 7800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 11600, 24, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 16900, 30, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_supplement_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (4, '강아지 영양제 상품2', '강아지의 영양제용 고급 상품입니다.', 23300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 11200, 22, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 16300, 20, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_supplement_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (4, '강아지 영양제 상품3', '강아지의 영양제용 고급 상품입니다.', 13500, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 17700, 44, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 20000, 20, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_supplement_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (4, '강아지 영양제 상품4', '강아지의 영양제용 고급 상품입니다.', 18100, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 22800, 39, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 5200, 8, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_supplement_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (4, '강아지 영양제 상품5', '강아지의 영양제용 고급 상품입니다.', 11800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 27000, 6, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 23900, 44, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_supplement_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (5, '강아지 장난감 상품1', '강아지의 장난감용 고급 상품입니다.', 18100, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 27000, 47, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 25400, 29, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_toy_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (5, '강아지 장난감 상품2', '강아지의 장난감용 고급 상품입니다.', 29600, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 22000, 28, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 16000, 18, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_toy_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (5, '강아지 장난감 상품3', '강아지의 장난감용 고급 상품입니다.', 9400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 15400, 24, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 22600, 8, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_toy_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (5, '강아지 장난감 상품4', '강아지의 장난감용 고급 상품입니다.', 16300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 29200, 43, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 13300, 50, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_toy_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (5, '강아지 장난감 상품5', '강아지의 장난감용 고급 상품입니다.', 16500, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 1800, 20, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 16600, 19, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_toy_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (6, '강아지 용품 상품1', '강아지의 용품용 고급 상품입니다.', 21200, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 1300, 32, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 3400, 31, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_goods_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (6, '강아지 용품 상품2', '강아지의 용품용 고급 상품입니다.', 14300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 20900, 50, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 15700, 21, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_goods_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (6, '강아지 용품 상품3', '강아지의 용품용 고급 상품입니다.', 20500, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 23300, 45, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 11500, 14, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_goods_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (6, '강아지 용품 상품4', '강아지의 용품용 고급 상품입니다.', 30000, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 18500, 7, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 27600, 42, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_goods_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (6, '강아지 용품 상품5', '강아지의 용품용 고급 상품입니다.', 22000, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 22000, 7, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 13000, 23, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_goods_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (8, '고양이 사료 상품1', '고양이의 사료용 고급 상품입니다.', 26400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 10900, 43, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 15600, 48, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_food_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (8, '고양이 사료 상품2', '고양이의 사료용 고급 상품입니다.', 19400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 16300, 44, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 11900, 24, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_food_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (8, '고양이 사료 상품3', '고양이의 사료용 고급 상품입니다.', 15800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 17600, 23, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 20400, 43, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_food_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (8, '고양이 사료 상품4', '고양이의 사료용 고급 상품입니다.', 5300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 9500, 43, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 28200, 32, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_food_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (8, '고양이 사료 상품5', '고양이의 사료용 고급 상품입니다.', 25900, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 19600, 6, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 15700, 9, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_food_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (9, '고양이 간식 상품1', '고양이의 간식용 고급 상품입니다.', 4100, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 27300, 5, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 8800, 29, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_snack_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (9, '고양이 간식 상품2', '고양이의 간식용 고급 상품입니다.', 6600, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 16500, 30, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 14400, 35, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_snack_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (9, '고양이 간식 상품3', '고양이의 간식용 고급 상품입니다.', 23300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 29700, 10, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 4100, 13, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_snack_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (9, '고양이 간식 상품4', '고양이의 간식용 고급 상품입니다.', 23400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 15600, 20, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 25200, 43, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_snack_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (9, '고양이 간식 상품5', '고양이의 간식용 고급 상품입니다.', 3900, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 27900, 10, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 21300, 18, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_snack_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (10, '고양이 영양제 상품1', '고양이의 영양제용 고급 상품입니다.', 24600, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 10200, 35, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 18900, 21, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_supplement_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (10, '고양이 영양제 상품2', '고양이의 영양제용 고급 상품입니다.', 24500, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 13000, 49, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 13500, 29, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_supplement_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (10, '고양이 영양제 상품3', '고양이의 영양제용 고급 상품입니다.', 29000, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 8000, 11, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 29000, 50, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_supplement_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (10, '고양이 영양제 상품4', '고양이의 영양제용 고급 상품입니다.', 7700, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 6900, 29, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 15900, 34, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_supplement_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (10, '고양이 영양제 상품5', '고양이의 영양제용 고급 상품입니다.', 23800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 13700, 33, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 18400, 27, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_supplement_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (11, '고양이 장난감 상품1', '고양이의 장난감용 고급 상품입니다.', 23800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 26000, 24, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 19600, 38, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_toy_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (11, '고양이 장난감 상품2', '고양이의 장난감용 고급 상품입니다.', 26600, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 18100, 10, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 25900, 42, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_toy_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (11, '고양이 장난감 상품3', '고양이의 장난감용 고급 상품입니다.', 10900, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 10200, 19, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 20900, 42, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_toy_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (11, '고양이 장난감 상품4', '고양이의 장난감용 고급 상품입니다.', 14400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 28100, 48, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 25400, 34, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_toy_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (11, '고양이 장난감 상품5', '고양이의 장난감용 고급 상품입니다.', 26700, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 16300, 48, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 25200, 6, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_toy_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (12, '고양이 용품 상품1', '고양이의 용품용 고급 상품입니다.', 5900, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 23900, 28, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 11900, 5, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_goods_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (12, '고양이 용품 상품2', '고양이의 용품용 고급 상품입니다.', 13800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 3300, 22, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 22400, 35, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_goods_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (12, '고양이 용품 상품3', '고양이의 용품용 고급 상품입니다.', 23400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 28200, 31, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 5600, 38, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_goods_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (12, '고양이 용품 상품4', '고양이의 용품용 고급 상품입니다.', 9200, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 10200, 46, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 18500, 15, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_goods_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (12, '고양이 용품 상품5', '고양이의 용품용 고급 상품입니다.', 16800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 3800, 30, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 17800, 47, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_goods_5.png', true);

-- 해시태그 매핑 추가
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('강아지', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('고양이', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('토끼', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('햄스터', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('기니피그', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('앵무새', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('도마뱀', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('고슴도치', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('페럿', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('거북이', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('말티즈', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('푸들', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('포메라니안', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('시바견', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('코숏', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('러시안블루', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('노르웨이숲', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('아비시니안', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('믹스견', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('반려동물', 0, NOW());

INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('사료추천', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('강아지간식', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('고양이간식', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('장난감', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('하네스', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('목줄', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('캣타워', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('자동급식기', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('자동급수기', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('배변패드', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('고양이모래', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('스크래쳐', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('이갈이장난감', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('슬링백', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('이동장', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('애견의류', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('고양이옷', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('영양제', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('헬스케어', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('펫템추천', 0, NOW());

INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('오늘의댕댕이', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('오늘의냥이', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('우리집고양이', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('우리집강아지', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('펫스타그램', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('냥스타그램', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('댕댕이그램', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('애견일상', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('반려일기', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('강아지브이로그', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('캣맘', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('강아지첫산책', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('냥줍', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('입양일기', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('반려동물자랑', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('반려동물사진', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('귀여운순간', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('반려동물훈련', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('강아지사회화', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('냥이놀이', 0, NOW());

INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('동물병원', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('펫병원예약', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('예방접종', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('중성화수술', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('슬개골탈구', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('피부병', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('귀청소', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('치석제거', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('눈물관리', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('건강검진', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('강아지진료', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('고양이진료', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('24시동물병원', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('응급진료', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('펫보험', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('병원리뷰', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('의료상담', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('건강상식', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('수의사상담', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('펫헬스케어', 0, NOW());

INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('산책코스추천', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('반려동물동반', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('펫프렌들리', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('펫카페', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('애견동반식당', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('반려동물호텔', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('펫스파', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('강아지수영장', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('강아지운동장', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('애견운동장', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('애견놀이터', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('캣카페', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('펫놀이터', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('반려동물동반여행', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('산책스타그램', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('강아지산책', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('고양이산책', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('펫캠핑', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('반려동물숙소', 0, NOW());
INSERT INTO hashtag (tag_name, tag_count, created_at) VALUES ('강아지펜션', 0, NOW());