-- 자동 생성된 더미 데이터
-- 기존 데이터가 없을 때만 삽입하도록 조건부 삽입

INSERT INTO item_category (parent_option, option_value) VALUES (NULL, '강아지');
INSERT INTO item_category (parent_option, option_value) VALUES (1, '사료');
INSERT INTO item_category (parent_option, option_value) VALUES (1, '간식');
INSERT INTO item_category (parent_option, option_value) VALUES (1, '영양제');
INSERT INTO item_category (parent_option, option_value) VALUES (1, '장난감');
INSERT INTO item_category (parent_option, option_value) VALUES (1, '용품');
INSERT INTO item_category (parent_option, option_value) VALUES (NULL, '고양이');
INSERT INTO item_category (parent_option, option_value) VALUES (7, '사료');
INSERT INTO item_category (parent_option, option_value) VALUES (7, '간식');
INSERT INTO item_category (parent_option, option_value) VALUES (7, '영양제');
INSERT INTO item_category (parent_option, option_value) VALUES (7, '장난감');
INSERT INTO item_category (parent_option, option_value) VALUES (7, '용품');
INSERT INTO item_category (parent_option, option_value) VALUES (NULL, '기타');
INSERT INTO item_category (parent_option, option_value) VALUES (13, '기타');


INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (2, '강아지 사료 상품1', '강아지의 사료용 고급 상품입니다.', 13200, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 5800, 17, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 29900, 24, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_food_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (2, '강아지 사료 상품2', '강아지의 사료용 고급 상품입니다.', 10200, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 4000, 25, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 22200, 34, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_food_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (2, '강아지 사료 상품3', '강아지의 사료용 고급 상품입니다.', 26700, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 24900, 7, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 15100, 8, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_food_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (2, '강아지 사료 상품4', '강아지의 사료용 고급 상품입니다.', 16700, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 10900, 27, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 29500, 50, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_food_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (2, '강아지 사료 상품5', '강아지의 사료용 고급 상품입니다.', 5300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 12700, 25, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 4000, 7, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_food_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (3, '강아지 간식 상품1', '강아지의 간식용 고급 상품입니다.', 16900, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 21100, 37, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 22700, 38, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_snack_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (3, '강아지 간식 상품2', '강아지의 간식용 고급 상품입니다.', 12200, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 26900, 15, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 14800, 26, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_snack_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (3, '강아지 간식 상품3', '강아지의 간식용 고급 상품입니다.', 19500, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 1000, 50, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 20200, 32, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_snack_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (3, '강아지 간식 상품4', '강아지의 간식용 고급 상품입니다.', 6300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 11000, 44, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 6000, 9, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_snack_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (3, '강아지 간식 상품5', '강아지의 간식용 고급 상품입니다.', 15400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 9300, 42, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 28400, 8, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_snack_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (4, '강아지 영양제 상품1', '강아지의 영양제용 고급 상품입니다.', 7800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 11600, 24, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 16900, 30, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_supplement_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (4, '강아지 영양제 상품2', '강아지의 영양제용 고급 상품입니다.', 23300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 11200, 22, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 16300, 20, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_supplement_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (4, '강아지 영양제 상품3', '강아지의 영양제용 고급 상품입니다.', 13500, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 17700, 44, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 20000, 20, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_supplement_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (4, '강아지 영양제 상품4', '강아지의 영양제용 고급 상품입니다.', 18100, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 22800, 39, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 5200, 8, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_supplement_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (4, '강아지 영양제 상품5', '강아지의 영양제용 고급 상품입니다.', 11800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 27000, 6, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 23900, 44, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_supplement_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (5, '강아지 장난감 상품1', '강아지의 장난감용 고급 상품입니다.', 18100, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 27000, 47, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 25400, 29, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_toy_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (5, '강아지 장난감 상품2', '강아지의 장난감용 고급 상품입니다.', 29600, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 22000, 28, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 16000, 18, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_toy_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (5, '강아지 장난감 상품3', '강아지의 장난감용 고급 상품입니다.', 9400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 15400, 24, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 22600, 8, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_toy_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (5, '강아지 장난감 상품4', '강아지의 장난감용 고급 상품입니다.', 16300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 29200, 43, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 13300, 50, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_toy_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (5, '강아지 장난감 상품5', '강아지의 장난감용 고급 상품입니다.', 16500, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 1800, 20, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 16600, 19, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_toy_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (6, '강아지 용품 상품1', '강아지의 용품용 고급 상품입니다.', 21200, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 1300, 32, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 3400, 31, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_goods_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (6, '강아지 용품 상품2', '강아지의 용품용 고급 상품입니다.', 14300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 20900, 50, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 15700, 21, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_goods_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (6, '강아지 용품 상품3', '강아지의 용품용 고급 상품입니다.', 20500, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 23300, 45, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 11500, 14, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_goods_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (6, '강아지 용품 상품4', '강아지의 용품용 고급 상품입니다.', 30000, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 18500, 7, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 27600, 42, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_goods_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (6, '강아지 용품 상품5', '강아지의 용품용 고급 상품입니다.', 22000, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 22000, 7, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 13000, 23, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/dog_goods_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (8, '고양이 사료 상품1', '고양이의 사료용 고급 상품입니다.', 26400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 10900, 43, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 15600, 48, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_food_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (8, '고양이 사료 상품2', '고양이의 사료용 고급 상품입니다.', 19400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 16300, 44, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 11900, 24, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_food_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (8, '고양이 사료 상품3', '고양이의 사료용 고급 상품입니다.', 15800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 17600, 23, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 20400, 43, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_food_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (8, '고양이 사료 상품4', '고양이의 사료용 고급 상품입니다.', 5300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 9500, 43, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 28200, 32, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_food_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (8, '고양이 사료 상품5', '고양이의 사료용 고급 상품입니다.', 25900, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 19600, 6, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 15700, 9, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_food_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (9, '고양이 간식 상품1', '고양이의 간식용 고급 상품입니다.', 4100, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 27300, 5, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 8800, 29, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_snack_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (9, '고양이 간식 상품2', '고양이의 간식용 고급 상품입니다.', 6600, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 16500, 30, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 14400, 35, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_snack_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (9, '고양이 간식 상품3', '고양이의 간식용 고급 상품입니다.', 23300, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 29700, 10, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 4100, 13, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_snack_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (9, '고양이 간식 상품4', '고양이의 간식용 고급 상품입니다.', 23400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 15600, 20, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 25200, 43, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_snack_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (9, '고양이 간식 상품5', '고양이의 간식용 고급 상품입니다.', 3900, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 27900, 10, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 21300, 18, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_snack_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (10, '고양이 영양제 상품1', '고양이의 영양제용 고급 상품입니다.', 24600, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 10200, 35, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 18900, 21, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_supplement_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (10, '고양이 영양제 상품2', '고양이의 영양제용 고급 상품입니다.', 24500, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 13000, 49, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 13500, 29, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_supplement_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (10, '고양이 영양제 상품3', '고양이의 영양제용 고급 상품입니다.', 29000, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 8000, 11, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 29000, 50, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_supplement_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (10, '고양이 영양제 상품4', '고양이의 영양제용 고급 상품입니다.', 7700, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 6900, 29, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 15900, 34, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_supplement_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (10, '고양이 영양제 상품5', '고양이의 영양제용 고급 상품입니다.', 23800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 13700, 33, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 18400, 27, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_supplement_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (11, '고양이 장난감 상품1', '고양이의 장난감용 고급 상품입니다.', 23800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 26000, 24, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 19600, 38, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_toy_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (11, '고양이 장난감 상품2', '고양이의 장난감용 고급 상품입니다.', 26600, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 18100, 10, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 25900, 42, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_toy_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (11, '고양이 장난감 상품3', '고양이의 장난감용 고급 상품입니다.', 10900, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 10200, 19, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 20900, 42, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_toy_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (11, '고양이 장난감 상품4', '고양이의 장난감용 고급 상품입니다.', 14400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 28100, 48, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 25400, 34, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_toy_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (11, '고양이 장난감 상품5', '고양이의 장난감용 고급 상품입니다.', 26700, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 16300, 48, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 25200, 6, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_toy_5.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (12, '고양이 용품 상품1', '고양이의 용품용 고급 상품입니다.', 5900, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 23900, 28, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 11900, 5, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_goods_1.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (12, '고양이 용품 상품2', '고양이의 용품용 고급 상품입니다.', 13800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 3300, 22, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 22400, 35, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_goods_2.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (12, '고양이 용품 상품3', '고양이의 용품용 고급 상품입니다.', 23400, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 28200, 31, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 5600, 38, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_goods_3.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (12, '고양이 용품 상품4', '고양이의 용품용 고급 상품입니다.', 9200, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 10200, 46, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 18500, 15, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_goods_4.png', true);
INSERT INTO items (category_id, item_name, item_description, item_price, item_status, is_active, item_reg_date, item_update_date) VALUES (12, '고양이 용품 상품5', '고양이의 용품용 고급 상품입니다.', 16800, 'SELL', true, NOW(), NOW());
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'S', 3800, 30, true);
INSERT INTO items_option (item_id, option_name, option_add_price, option_stock, is_active) VALUES ((SELECT MAX(item_id) FROM items), 'M', 17800, 47, true);
INSERT INTO item_image (item_id, item_image_url, is_rep) VALUES ((SELECT MAX(item_id) FROM items), '/images/item/cat_goods_5.png', true);

